BEGIN;

-- CREATE TABLE "apogeeObject" ---------------------------------
CREATE TABLE "public"."apogeeObject" ( 
	"apogee_id" Character Varying,
	"target_id" Character Varying,
	"alt_id" Character Varying,
	"location_id" Bigint,
	"ra" Double Precision,
	"dec" Double Precision,
	"j" Real,
	"j_err" Real,
	"h" Real,
	"src_h" Character Varying,
	"h_err" Real,
	"k" Real,
	"k_err" Real,
	"irac_3_6" Real,
	"irac_3_6_err" Real,
	"irac_4_5" Real,
	"irac_4_5_err" Real,
	"src_4_5" Character Varying,
	"irac_5_8" Real,
	"irac_5_8_err" Real,
	"irac_8_0" Real,
	"irac_8_0_err" Real,
	"wise_4_5" Real,
	"wise_4_5_err" Real,
	"ak_wise" Real,
	"sfd_ebv" Real,
	"wash_m" Real,
	"wash_m_err" Real,
	"wash_t2" Real,
	"wash_t2_err" Real,
	"DDO51" Real,
	"DDO51_err" Real,
	"wash_ddo51_giant_flag" Integer,
	"wash_ddo51_star_flag" Integer,
	"targ_4_5" Real,
	"targ_4_5_err" Real,
	"ak_targ" Real,
	"ak_targ_method" Character Varying,
	"pmra" Real,
	"pmra_err" Real,
	"pmdec" Real,
	"pmdec_err" Real,
	"pm_src" Character Varying,
	"tmass_a" Character Varying,
	"tmass_pxpa" Real,
	"tmass_prox" Real,
	"tmass_phqual" Character Varying,
	"tmass_rdflg" Character Varying,
	"tmass_ccflg" Character Varying,
	"tmass_extkey" Bigint,
	"tmass_gal_contam" Character Varying );
 ;
-- -------------------------------------------------------------

COMMIT;
