CREATE TABLE "public"."apogeeStar" ( 
"apstar_id" CHARACTER VARYING( 64 ) NOT NULL,
"target_id" CHARACTER VARYING( 64 ) NOT NULL,
"file" CHARACTER VARYING( 2044 ) NOT NULL,
"reduction_id" CHARACTER VARYING( 64 ) NOT NULL,
"apogee_id" CHARACTER VARYING( 32 ) NOT NULL,
"telescope" CHARACTER VARYING( 32 ) NOT NULL,
"location_id" BIGINT DEFAULT 8 NOT NULL,
"field" CHARACTER VARYING( 100 ) NOT NULL ,
"ra"	FLOAT	(8),
"dec"	FLOAT	(8),	
"glon"	FLOAT	(8),
"glat"	FLOAT	(8),
"apogee_target1"	BIGINT,
"apogee_target2"	BIGINT,
"apogee_target3"	BIGINT,
"apogee2_target1"	BIGINT,
"apogee2_target2"	BIGINT,
"apogee2_target3"	BIGINT,
"min_h"	REAL	,
"max_h"	REAL	,
"min_jk"	REAL	 ,	 
"max_jk"	REAL	 ,	 
"survey"	VARCHAR	(100)	 ,	 
"extratarg"	BIGINT		 ,
"nvisits"	BIGINT		 ,	 
"commiss"	BIGINT		 ,	 
"snr"	REAL		 	 ,	
"starflag"	BIGINT		,
"andflag"	BIGINT		 ,	
"vhelio_avg"	REAL,	
"vscatter"	REAL		,
"verr"	REAL		,
"verr_med"	REAL	,
"synthvhelio_avg"	REAL	,
"synthvscatter"	REAL		,
"synthverr"	REAL		,
"synthverr_med"	REAL	,
"rv_teff"	REAL		,
"rv_logg"	REAL		,
"rv_feh"	REAL		,
"rv_ccfwhm"	REAL	,
"rv_autofwhm"	REAL	,
"synthscatter"	REAL	,
"stablerv_chi2"	REAL	,
"stablerv_rchi2"	REAL	,
"chi2_threshold"	REAL	,
"stablerv_chi2_prob"	REAL	,
"apstar_version"	VARCHAR		 ,
"htmID"	BIGINT		 	 	);
 ;
